// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD7G7VmlBF6nfFc8OcKvCcPaLVaF8FgWTI',
    appId: '1:707001280558:web:1a427dfbe1b0de82c157bf',
    messagingSenderId: '707001280558',
    projectId: 'bothcmus',
    authDomain: 'bothcmus.firebaseapp.com',
    storageBucket: 'bothcmus.firebasestorage.app',
    measurementId: 'G-W34EMJY68Q',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCNzSCAgWzCGSEp1WXBozM9S90hYyqcP3k',
    appId: '1:707001280558:android:1806f6e0c607fc94c157bf',
    messagingSenderId: '707001280558',
    projectId: 'bothcmus',
    storageBucket: 'bothcmus.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCEl3UcR4KLhotT9SXgbMhdG5e5_zDcZDk',
    appId: '1:707001280558:ios:708ba407c45ec7e6c157bf',
    messagingSenderId: '707001280558',
    projectId: 'bothcmus',
    storageBucket: 'bothcmus.firebasestorage.app',
    iosBundleId: 'com.example.knowledgeBasedBot',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCEl3UcR4KLhotT9SXgbMhdG5e5_zDcZDk',
    appId: '1:707001280558:ios:708ba407c45ec7e6c157bf',
    messagingSenderId: '707001280558',
    projectId: 'bothcmus',
    storageBucket: 'bothcmus.firebasestorage.app',
    iosBundleId: 'com.example.knowledgeBasedBot',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD7G7VmlBF6nfFc8OcKvCcPaLVaF8FgWTI',
    appId: '1:707001280558:web:c7128bf1a50967a8c157bf',
    messagingSenderId: '707001280558',
    projectId: 'bothcmus',
    authDomain: 'bothcmus.firebaseapp.com',
    storageBucket: 'bothcmus.firebasestorage.app',
    measurementId: 'G-L1B29XLQEP',
  );
}
